# Generated by Django 4.2.9 on 2024-01-23 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved',
        ),
        migrations.AddField(
            model_name='post',
            name='saved_post',
            field=models.ManyToManyField(blank=True, related_name='post_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
